development:
  adapter: mysql2
  database: campi_development
  host: localhost
  port: 3306
  username: root
  password:

test:
  adapter: mysql2
  database: campi_test
  host: localhost
  port: 3306
  username: root
  password:

production:
  adapter: mysql2
  database: campi_production
  host: localhost
  port: 3306
  username: root
  password:

